#!/usr/bin/env python
import os
import numpy as np
import matplotlib.pyplot as plt
import trishul.dbson as tdb

def parseargs():
    import argparse as arp
    ap = arp.ArgumentParser (prog='tsbt4', description='Trishul handy tool for bowtie plane four plot.', epilog='Part of Trishul')
    add = ap.add_argument
    add('dbson', help = 'List of fbsons', nargs='+')
    add("--dir", help='Output directory',dest='dir', default="./")
    add("--ext", help='Plot format',dest='ext', default="png")
    return ap.parse_args ()

if __name__ == "__main__":
    args = parseargs ()
    for dbs in args.dbson:
        with tdb.DBSON (dbs) as x:
            # data planes
            ibt  = x.bt
            jbt  = np.flipud ( np.fliplr ( ibt ) )
            mbt  = ibt + jbt
            nbt  = ibt - jbt
            # axes
            dms = np.arange (x.ndm) * x.dmoff
            dms += x.dm1
            times = np.arange (x.nsamps) * x.tsamp
            # plotings
            fig, ax = plt.subplots (2,2, sharex=True, sharey=True)
            ax[0,0].imshow (ibt, aspect='auto', origin='lower',extent=[times[0], times[-1], dms[0], dms[-1]])
            ax[0,1].imshow (jbt, aspect='auto', origin='lower',extent=[times[0], times[-1], dms[0], dms[-1]])
            ax[1,0].imshow (ibt+jbt, aspect='auto', origin='lower',extent=[times[0], times[-1], dms[0], dms[-1]])
            ax[1,1].imshow (ibt-jbt, aspect='auto', origin='lower',extent=[times[0], times[-1], dms[0], dms[-1]])
            # labels
            ax[1,0].set_xlabel ("Time [s]")
            ax[1,1].set_xlabel ("Time [s]")
            ax[1,0].set_ylabel ("DM [pc/cc]")
            ax[0,0].set_ylabel ("DM [pc/cc]")
            # titles
            ax[0,0].set_title ("Original")
            ax[0,1].set_title ("-1")
            ax[1,0].set_title ("+")
            ax[1,1].set_title ("-")
            fig.suptitle (dbs)
            # tight layout 
            # fig.tight_layout()
            # save
            fn,_ = os.path.splitext (os.path.basename(dbs))
            plt.savefig (
                os.path.join (args.dir, fn+"_bt4."+args.ext)
            )

