#!/usr/bin/env python

import trishul.dbson as tdb
import argparse

def parse_args ():
  ap = argparse.ArgumentParser(prog='tsdbson', description='Trishul tool for dbson creation.', epilog='Part of Trishul')
  add = ap.add_argument
  add('fbson', help = 'List of fbsons', nargs='+')
  add("--dir", help='Output directory',dest='dir')
  # done
  return ap.parse_args()

if __name__ == "__main__":
  args = parse_args ()
  for fbs in args.fbson:
    x = tdb.DBSON (fbs)
    tdb.WriteDBSON (x, outdir = args.dir)


