#!/usr/bin/env python
import numpy as np
import trishul.dbson as tdb
import argparse
import pickle as pkl

def parse_args ():
    ap = argparse.ArgumentParser(prog='tsdb_add', description='Trishul tool for dbson coaddition.', epilog='Part of Trishul')
    add = ap.add_argument
    add('dbson', help = 'List of dbsons', nargs='+')
    add('-o', help='Filename', dest='ofile')
    # done
    return ap.parse_args()

if __name__ == "__main__":
    args = parse_args ()
    ndbs = len(args.dbson)
    if ndbs == 1:
        with open (args.dbson[0], "r") as f:
            LIST = list (map (lambda x : x.strip(), f.readlines ()))
        ndbs = len (LIST)
    else:
        LIST = args.dbson
    ##
    BUNCH = []
    for il in LIST:
        with tdb.DBSON (il) as db:
            BUNCH.append (db)
    #
    with open (args.ofile, "wb") as f:
        pkl.dump (BUNCH, f)
    



