#!/usr/bin/env python2.7

import trishul.fbson   as tfb
import trishul.features as tfx

Features = ['lyon']

def parse_args ():
  '''parse args''' 
  import argparse 
  ap = argparse.ArgumentParser(prog='tsfeature', description='Trishul tool for feature extraction.', epilog='Part of Trishul')
  add = ap.add_argument
  add('fex', help = 'Set of features to extract', type=str, choices=Features)
  add('fbson', help = 'List of fbsons', nargs='+')
  # run n multiple processes
  add('-n,--nproc', help = 'Number of processes to launch.', default=1, dest='nproc')
  # done
  return ap.parse_args()


if __name__ == "__main__":
  args = parse_args()
  ll = tfx.Lyon ("bigtest")
  for ff in args.fbson:
    print ff
    xx = tfb.FBSON (ff, loadFB=True)
    print ff
    ll.Extract (xx)
    del xx
  ll.Write ()
      

  
